# CS 180 - MP 2

Pascua, Primrose F.

Saliba, Martin Thomas D.

### Data Preprocessing
1. Initialize
               a. pandas - pd functions
               b. numpy - numpy functions, np.reshape
               c. csv - import and export csv files

In [1]:
import pandas as pd
import numpy as np
import csv

 2. Dropped
                a. Unnamed: 0 - index of .csv file
                b. Company - unnecessary
                c. Product - unnecessary (name)
                d. Weight - unnecessary
                e. Inches

In [2]:
data = pd.read_csv("laptops.csv", header=0)
data.drop(['Unnamed: 0', 'Company', 'Product', 'Weight', 'Inches'], axis = 1, inplace = True)

In [3]:
data

TypeName                            ScreenResolution  \
0              Ultrabook          IPS Panel Retina Display 2560x1600   
1              Ultrabook                                    1440x900   
2               Notebook                           Full HD 1920x1080   
3              Ultrabook          IPS Panel Retina Display 2880x1800   
4              Ultrabook          IPS Panel Retina Display 2560x1600   
5               Notebook                                    1366x768   
6              Ultrabook          IPS Panel Retina Display 2880x1800   
7              Ultrabook                                    1440x900   
8              Ultrabook                           Full HD 1920x1080   
9              Ultrabook                 IPS Panel Full HD 1920x1080   
10              Notebook                                    1366x768   
11              Notebook                           Full HD 1920x1080   
12             Ultrabook          IPS Panel Retina Display 2880x1800   
13              Notebook                           Full HD 1920x1080   
14             Ultrabook          IPS Panel Retina Display 2304x1440   
15             Ultrabook          IPS Panel Retina Display 2560x1600   
16              Notebook                           Full HD 1920x1080   
17             Ultrabook          IPS Panel Retina Display 2880x1800   
18              Notebook                           Full HD 1920x1080   
19             Ultrabook   IPS Panel Full HD / Touchscreen 1920x1080   
20               Netbook                                    1366x768   
21                Gaming                 IPS Panel Full HD 1920x1080   
22              Notebook                                    1366x768   
23    2 in 1 Convertible             Full HD / Touchscreen 1920x1080   
24             Ultrabook                           Full HD 1920x1080   
25              Notebook                                    1366x768   
26             Ultrabook                                    1440x900   
27              Notebook                           Full HD 1920x1080   
28             Ultrabook                           Full HD 1920x1080   
29              Notebook                           Full HD 1920x1080   
...                  ...                                         ...   
1273            Notebook                                    1366x768   
1274            Notebook                                    1366x768   
1275           Ultrabook                 IPS Panel Full HD 1920x1080   
1276            Notebook                                    1366x768   
1277            Notebook                                    1366x768   
1278            Notebook                                    1366x768   
1279            Notebook                 IPS Panel Full HD 1920x1080   
1280            Notebook                           Full HD 1920x1080   
1281            Notebook                                    1366x768   
1282             Netbook                                    1366x768   
1283            Notebook                                    1366x768   
1284  2 in 1 Convertible   IPS Panel Full HD / Touchscreen 1920x1080   
1285  2 in 1 Convertible  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1286            Notebook                                    1366x768   
1287            Notebook                                    1366x768   
1288            Notebook                                    1366x768   
1289           Ultrabook                 IPS Panel Full HD 1920x1080   
1290            Notebook                                    1366x768   
1291            Notebook                                    1366x768   
1292            Notebook                                    1366x768   
1293            Notebook                 IPS Panel Full HD 1920x1080   
1294            Notebook                           Full HD 1920x1080   
1295            Notebook                                    1366x768   
1296             Netbook                                

### TypeName

Convert entries into numerical data.

In [4]:
list(data['TypeName'].unique())

['Ultrabook',
 'Notebook',
 'Netbook',
 'Gaming',
 '2 in 1 Convertible',
 'Workstation']

In [5]:
temp = list(data['TypeName'].unique())
data.TypeName = data.TypeName.replace(temp, [1,2,3,4,5,6])

In [6]:
data

TypeName                            ScreenResolution  \
0            1          IPS Panel Retina Display 2560x1600   
1            1                                    1440x900   
2            2                           Full HD 1920x1080   
3            1          IPS Panel Retina Display 2880x1800   
4            1          IPS Panel Retina Display 2560x1600   
5            2                                    1366x768   
6            1          IPS Panel Retina Display 2880x1800   
7            1                                    1440x900   
8            1                           Full HD 1920x1080   
9            1                 IPS Panel Full HD 1920x1080   
10           2                                    1366x768   
11           2                           Full HD 1920x1080   
12           1          IPS Panel Retina Display 2880x1800   
13           2                           Full HD 1920x1080   
14           1          IPS Panel Retina Display 2304x1440   
15           1          IPS Panel Retina Display 2560x1600   
16           2                           Full HD 1920x1080   
17           1          IPS Panel Retina Display 2880x1800   
18           2                           Full HD 1920x1080   
19           1   IPS Panel Full HD / Touchscreen 1920x1080   
20           3                                    1366x768   
21           4                 IPS Panel Full HD 1920x1080   
22           2                                    1366x768   
23           5             Full HD / Touchscreen 1920x1080   
24           1                           Full HD 1920x1080   
25           2                                    1366x768   
26           1                                    1440x900   
27           2                           Full HD 1920x1080   
28           1                           Full HD 1920x1080   
29           2                           Full HD 1920x1080   
...        ...                                         ...   
1273         2                                    1366x768   
1274         2                                    1366x768   
1275         1                 IPS Panel Full HD 1920x1080   
1276         2                                    1366x768   
1277         2                                    1366x768   
1278         2                                    1366x768   
1279         2                 IPS Panel Full HD 1920x1080   
1280         2                           Full HD 1920x1080   
1281         2                                    1366x768   
1282         3                                    1366x768   
1283         2                                    1366x768   
1284         5   IPS Panel Full HD / Touchscreen 1920x1080   
1285         5  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1286         2                                    1366x768   
1287         2                                    1366x768   
1288         2                                    1366x768   
1289         1                 IPS Panel Full HD 1920x1080   
1290         2                                    1366x768   
1291         2                                    1366x768   
1292         2                                    1366x768   
1293         2                 IPS Panel Full HD 1920x1080   
1294         2                           Full HD 1920x1080   
1295         2                                    1366x768   
1296         3                                    1366x768   
1297         2                                    1366x768   
1298         5   IPS Panel Full HD / Touchscreen 1920x1080   
1299         5  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300         2                                    1366x768   
1301         2                                    1366x768   
1302         2                                    1366x768   

                                       Cpu   Ram                  Memory  \
0                     Intel Core i5 2.3GHz   8GB               128GB SSD   
1        

### OpSys

preprocess entries on OpSys column.

In [7]:
list(data['OpSys'].unique())

['macOS',
 'No OS',
 'Windows 10',
 'Mac OS X',
 'Linux',
 'Android',
 'Windows 10 S',
 'Chrome OS',
 'Windows 7']

Convert the entries on OpSys into numerical data and reduce to only Windows(1), Mac(2), Linux(3), and Others(4)

In [8]:
data.OpSys = data.OpSys.replace({'Windows 10':1, 'Windows 10 S':1, 'Windows 7':1, 'macOS':2, 'Mac OS X':2, 'Linux':3, 'Android':4, 'Chrome OS':4, 'No OS': 4})
list(data['OpSys'].unique())

[2, 4, 1, 3]

### RAM

Strip the unit of memory. All entries are GB.

In [9]:
data['Ram'] = data['Ram'].str.rstrip('GB').astype(float)

### Price

Change Price entries to range. (799 and below Low; 800-1499 Average; 1500 and above High)

Change the Label of the column from Price_euros to Price

In [10]:
copy = data.Price_euros.copy()
data.Price_euros = data.Price_euros.mask(copy<800, 'Low')
data.Price_euros = data.Price_euros.mask((copy<1500)&(copy>799), 'Average')
data.Price_euros = data.Price_euros.mask(copy>1499, 'High')
data.rename(columns={'Price_euros':'Price'},inplace = True)

### CPU
Convert entries to numerical.

In [11]:
list(data['Cpu'].unique())

['Intel Core i5 2.3GHz',
 'Intel Core i5 1.8GHz',
 'Intel Core i5 7200U 2.5GHz',
 'Intel Core i7 2.7GHz',
 'Intel Core i5 3.1GHz',
 'AMD A9-Series 9420 3GHz',
 'Intel Core i7 2.2GHz',
 'Intel Core i7 8550U 1.8GHz',
 'Intel Core i5 8250U 1.6GHz',
 'Intel Core i3 6006U 2GHz',
 'Intel Core i7 2.8GHz',
 'Intel Core M m3 1.2GHz',
 'Intel Core i7 7500U 2.7GHz',
 'Intel Core i7 2.9GHz',
 'Intel Core i3 7100U 2.4GHz',
 'Intel Atom x5-Z8350 1.44GHz',
 'Intel Core i5 7300HQ 2.5GHz',
 'AMD E-Series E2-9000e 1.5GHz',
 'Intel Core i5 1.6GHz',
 'Intel Core i7 8650U 1.9GHz',
 'Intel Atom x5-Z8300 1.44GHz',
 'AMD E-Series E2-6110 1.5GHz',
 'AMD A6-Series 9220 2.5GHz',
 'Intel Celeron Dual Core N3350 1.1GHz',
 'Intel Core i3 7130U 2.7GHz',
 'Intel Core i7 7700HQ 2.8GHz',
 'Intel Core i5 2.0GHz',
 'AMD Ryzen 1700 3GHz',
 'Intel Pentium Quad Core N4200 1.1GHz',
 'Intel Atom x5-Z8550 1.44GHz',
 'Intel Celeron Dual Core N3060 1.6GHz',
 'Intel Core i5 1.3GHz',
 'AMD FX 9830P 3GHz',
 'Intel Core i7 7560U 2.4

In [12]:
data = data[~data['Cpu'].str.contains('Samsung')]

data.loc[data['Cpu'].str.contains('i3', na = False), 'Cpu'] = 1
data.loc[data['Cpu'].str.contains('i5', na = False), 'Cpu'] = 2
data.loc[data['Cpu'].str.contains('i7', na = False), 'Cpu'] = 3
data.loc[data['Cpu'].str.contains('Atom', na = False), 'Cpu'] = 4
data.loc[data['Cpu'].str.contains('Celeron Dual Core', na = False), 'Cpu'] = 5
data.loc[data['Cpu'].str.contains('Celeron Quad Core', na = False), 'Cpu'] = 6
data.loc[data['Cpu'].str.contains('Pentium Dual Core', na = False), 'Cpu'] = 7
data.loc[data['Cpu'].str.contains('Pentium Quad Core', na = False), 'Cpu'] = 8
data.loc[data['Cpu'].str.contains('Xeon', na = False), 'Cpu'] = 9
data.loc[data['Cpu'].str.contains('Core M', na = False), 'Cpu'] = 10
data.loc[data['Cpu'].str.contains('AMD', na = False), 'Cpu'] = 11
list(data['Cpu'].unique())


c:\python27\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


[2, 3, 11, 1, 10, 4, 5, 8, 9, 6, 7]

In [13]:
data

TypeName                            ScreenResolution  Cpu   Ram  \
0            1          IPS Panel Retina Display 2560x1600    2   8.0   
1            1                                    1440x900    2   8.0   
2            2                           Full HD 1920x1080    2   8.0   
3            1          IPS Panel Retina Display 2880x1800    3  16.0   
4            1          IPS Panel Retina Display 2560x1600    2   8.0   
5            2                                    1366x768   11   4.0   
6            1          IPS Panel Retina Display 2880x1800    3  16.0   
7            1                                    1440x900    2   8.0   
8            1                           Full HD 1920x1080    3  16.0   
9            1                 IPS Panel Full HD 1920x1080    2   8.0   
10           2                                    1366x768    2   4.0   
11           2                           Full HD 1920x1080    1   4.0   
12           1          IPS Panel Retina Display 2880x1800    3  16.0   
13           2                           Full HD 1920x1080    1   4.0   
14           1          IPS Panel Retina Display 2304x1440   10   8.0   
15           1          IPS Panel Retina Display 2560x1600    2   8.0   
16           2                           Full HD 1920x1080    3   8.0   
17           1          IPS Panel Retina Display 2880x1800    3  16.0   
18           2                           Full HD 1920x1080    1   8.0   
19           1   IPS Panel Full HD / Touchscreen 1920x1080    2   8.0   
20           3                                    1366x768    4   2.0   
21           4                 IPS Panel Full HD 1920x1080    2   8.0   
22           2                                    1366x768   11   4.0   
23           5             Full HD / Touchscreen 1920x1080    2   8.0   
24           1                           Full HD 1920x1080    3   8.0   
25           2                                    1366x768    1   4.0   
26           1                                    1440x900    2   8.0   
27           2                           Full HD 1920x1080    2   8.0   
28           1                           Full HD 1920x1080    3   8.0   
29           2                           Full HD 1920x1080    2   8.0   
...        ...                                         ...  ...   ...   
1273         2                                    1366x768    3   6.0   
1274         2                                    1366x768    5   4.0   
1275         1                 IPS Panel Full HD 1920x1080   10   8.0   
1276         2                                    1366x768    1   6.0   
1277         2                                    1366x768    5   4.0   
1278         2                                    1366x768    5   2.0   
1279         2                 IPS Panel Full HD 1920x1080    3   8.0   
1280         2                           Full HD 1920x1080   11   6.0   
1281         2                                    1366x768    3   8.0   
1282         3                                    1366x768    5   2.0   
1283         2                                    1366x768    3   4.0   
1284         5   IPS Panel Full HD / Touchscreen 1920x1080    3   4.0   
1285         5  IPS Panel Quad HD+ / Touchscreen 3200x1800    3  16.0   
1286         2                                    1366x768    5   2.0   
1287         2                                    1366x768    3   6.0   
1288         2                                    1366x768    5   4.0   
1289         1                 IPS Panel Full HD 1920x1080   10   8.0   
1290         2                                    1366x768    1   6.0   
1291         2                                    1366x768    5   4.0   
1292         2                                    1366x768    5   2.0   
1293         2                 IPS Panel Full HD 1920x1080    3   8.0   
1294         2                           Full HD 1920x1080   11   6.0   
1295         2                                    1366x768    3 

### ScreenResolution

convert to numerical.

In [14]:
list(data['ScreenResolution'].unique())

['IPS Panel Retina Display 2560x1600',
 '1440x900',
 'Full HD 1920x1080',
 'IPS Panel Retina Display 2880x1800',
 '1366x768',
 'IPS Panel Full HD 1920x1080',
 'IPS Panel Retina Display 2304x1440',
 'IPS Panel Full HD / Touchscreen 1920x1080',
 'Full HD / Touchscreen 1920x1080',
 'Touchscreen / Quad HD+ 3200x1800',
 'IPS Panel Touchscreen 1920x1200',
 'Touchscreen 2256x1504',
 'Quad HD+ / Touchscreen 3200x1800',
 'IPS Panel 1366x768',
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
 'IPS Panel Full HD 2160x1440',
 '4K Ultra HD / Touchscreen 3840x2160',
 'Touchscreen 2560x1440',
 '1600x900',
 'IPS Panel 4K Ultra HD 3840x2160',
 '4K Ultra HD 3840x2160',
 'Touchscreen 1366x768',
 'IPS Panel Full HD 1366x768',
 'IPS Panel 2560x1440',
 'IPS Panel Full HD 2560x1440',
 'IPS Panel Retina Display 2736x1824',
 'Touchscreen 2400x1600',
 '2560x1440',
 'IPS Panel Quad HD+ 2560x1440',
 'IPS Panel Quad HD+ 3200x1800',
 'IPS Panel Quad HD+ / Touchscreen 3200x1800',
 'IPS Panel Touchscreen 1366x768',


2560x1600 -> 1
1440x900 -> 2
2880x1800 -> 3
1920x1080 -> 4
2304x1440 -> 5
1366x768 -> 6
3200x1800 -> 7
2256x1504 -> 8
3840x2160 -> 9
2160x1440 -> 10
2560x1440 -> 11
1600x900 -> 12
2736x1824 -> 13
1920x1200 -> 14

In [15]:
data.loc[data['ScreenResolution'].str.contains('1366x768', na = False), 'ScreenResolution'] = 1
data.loc[data['ScreenResolution'].str.contains('1440x900', na = False), 'ScreenResolution'] = 2
data.loc[data['ScreenResolution'].str.contains('1600x900', na = False), 'ScreenResolution'] = 3
data.loc[data['ScreenResolution'].str.contains('1920x1080', na = False), 'ScreenResolution'] = 4
data.loc[data['ScreenResolution'].str.contains('1920x1200', na = False), 'ScreenResolution'] = 5
data.loc[data['ScreenResolution'].str.contains('2160x1440', na = False), 'ScreenResolution'] = 6
data.loc[data['ScreenResolution'].str.contains('2256x1504', na = False), 'ScreenResolution'] = 7
data.loc[data['ScreenResolution'].str.contains('2304x1440', na = False), 'ScreenResolution'] = 8
data.loc[data['ScreenResolution'].str.contains('2400x1600', na = False), 'ScreenResolution'] = 9
data.loc[data['ScreenResolution'].str.contains('2560x1440', na = False), 'ScreenResolution'] =10
data.loc[data['ScreenResolution'].str.contains('2560x1600', na = False), 'ScreenResolution'] = 11
data.loc[data['ScreenResolution'].str.contains('2736x1824', na = False), 'ScreenResolution'] = 12
data.loc[data['ScreenResolution'].str.contains('2880x1800', na = False), 'ScreenResolution'] = 13
data.loc[data['ScreenResolution'].str.contains('3200x1800', na = False), 'ScreenResolution'] = 14
data.loc[data['ScreenResolution'].str.contains('3840x2160', na = False), 'ScreenResolution'] = 15


list(data['ScreenResolution'].unique())

[11, 2, 4, 13, 1, 8, 14, 5, 7, 15, 6, 10, 3, 12, 9]

In [16]:
data

TypeName  ScreenResolution  Cpu   Ram                  Memory  \
0            1                11    2   8.0               128GB SSD   
1            1                 2    2   8.0     128GB Flash Storage   
2            2                 4    2   8.0               256GB SSD   
3            1                13    3  16.0               512GB SSD   
4            1                11    2   8.0               256GB SSD   
5            2                 1   11   4.0               500GB HDD   
6            1                13    3  16.0     256GB Flash Storage   
7            1                 2    2   8.0     256GB Flash Storage   
8            1                 4    3  16.0               512GB SSD   
9            1                 4    2   8.0               256GB SSD   
10           2                 1    2   4.0               500GB HDD   
11           2                 4    1   4.0               500GB HDD   
12           1                13    3  16.0               256GB SSD   
13           2                 4    1   4.0               256GB SSD   
14           1                 8   10   8.0               256GB SSD   
15           1                11    2   8.0               256GB SSD   
16           2                 4    3   8.0               256GB SSD   
17           1                13    3  16.0               512GB SSD   
18           2                 4    1   8.0                 1TB HDD   
19           1                 4    2   8.0               128GB SSD   
20           3                 1    4   2.0      32GB Flash Storage   
21           4                 4    2   8.0    128GB SSD +  1TB HDD   
22           2                 1   11   4.0               500GB HDD   
23           5                 4    2   8.0               256GB SSD   
24           1                 4    3   8.0               256GB SSD   
25           2                 1    1   4.0                 1TB HDD   
26           1                 2    2   8.0     128GB Flash Storage   
27           2                 4    2   8.0               256GB SSD   
28           1                 4    3   8.0  256GB SSD +  256GB SSD   
29           2                 4    2   8.0                 1TB HDD   
...        ...               ...  ...   ...                     ...   
1273         2                 1    3   6.0                 1TB HDD   
1274         2                 1    5   4.0               500GB HDD   
1275         1                 4   10   8.0               512GB SSD   
1276         2                 1    1   6.0                 1TB HDD   
1277         2                 1    5   4.0               500GB HDD   
1278         2                 1    5   2.0               500GB HDD   
1279         2                 4    3   8.0                 1TB HDD   
1280         2                 4   11   6.0            1.0TB Hybrid   
1281         2                 1    3   8.0                 1TB HDD   
1282         3                 1    5   2.0      32GB Flash Storage   
1283         2                 1    3   4.0               500GB HDD   
1284         5                 4    3   4.0               128GB SSD   
1285         5                14    3  16.0               512GB SSD   
1286         2                 1    5   2.0      64GB Flash Storage   
1287         2                 1    3   6.0                 1TB HDD   
1288         2                 1    5   4.0               500GB HDD   
1289         1                 4   10   8.0               512GB SSD   
1290         2                 1    1   6.0                 1TB HDD   
1291         2                 1    5   4.0               500GB HDD   
1292         2                 1    5   2.0               500GB HDD   
1293         2                 4    3   8.0                 1TB HDD   
1294         2                 4   11   6.0            1.0TB Hybrid   
1295         2                 1    3   8.0                 1TB HDD   
1296         3                 1    5   2.0      32GB Flash Storage   
1297         2                

### Memory

1TB and above -> High Memory (1)
greater than 200GB and less than 1TB -> Average Memory (2)
Below 200 GB -> Low Memory (3)

In [17]:
data.loc[data['Memory'].str.contains('TB', na = False), 'Memory'] = 1
data.loc[data['Memory']=='512GB SSD +  512GB SSD', 'Memory'] = 1
data.loc[data['Memory'].str.contains('512GB +', na = False), 'Memory'] = 2
data.loc[data['Memory'].str.contains('240GB', na = False), 'Memory'] = 2
data.loc[data['Memory'].str.contains('256GB', na = False), 'Memory'] = 2
data.loc[data['Memory'].str.contains('500GB', na = False), 'Memory'] = 2
data.loc[data['Memory'].str.contains('508GB', na = False), 'Memory'] = 2
data.loc[data['Memory'].str.contains('128GB', na = False), 'Memory'] = 3
data.loc[data['Memory'].str.contains('32GB', na = False), 'Memory'] = 3
data.loc[data['Memory'].str.contains('64GB', na = False), 'Memory'] = 3
data.loc[data['Memory'].str.contains('180GB', na = False), 'Memory'] = 3
data.loc[data['Memory'].str.contains('8GB', na = False), 'Memory'] = 3
data.loc[data['Memory'].str.contains('16GB', na = False), 'Memory'] = 3

list(data['Memory'].unique())

[3, 2, 1]

In [18]:
data

TypeName  ScreenResolution  Cpu   Ram  Memory  \
0            1                11    2   8.0       3   
1            1                 2    2   8.0       3   
2            2                 4    2   8.0       2   
3            1                13    3  16.0       2   
4            1                11    2   8.0       2   
5            2                 1   11   4.0       2   
6            1                13    3  16.0       2   
7            1                 2    2   8.0       2   
8            1                 4    3  16.0       2   
9            1                 4    2   8.0       2   
10           2                 1    2   4.0       2   
11           2                 4    1   4.0       2   
12           1                13    3  16.0       2   
13           2                 4    1   4.0       2   
14           1                 8   10   8.0       2   
15           1                11    2   8.0       2   
16           2                 4    3   8.0       2   
17           1                13    3  16.0       2   
18           2                 4    1   8.0       1   
19           1                 4    2   8.0       3   
20           3                 1    4   2.0       3   
21           4                 4    2   8.0       1   
22           2                 1   11   4.0       2   
23           5                 4    2   8.0       2   
24           1                 4    3   8.0       2   
25           2                 1    1   4.0       1   
26           1                 2    2   8.0       3   
27           2                 4    2   8.0       2   
28           1                 4    3   8.0       2   
29           2                 4    2   8.0       1   
...        ...               ...  ...   ...     ...   
1273         2                 1    3   6.0       1   
1274         2                 1    5   4.0       2   
1275         1                 4   10   8.0       2   
1276         2                 1    1   6.0       1   
1277         2                 1    5   4.0       2   
1278         2                 1    5   2.0       2   
1279         2                 4    3   8.0       1   
1280         2                 4   11   6.0       1   
1281         2                 1    3   8.0       1   
1282         3                 1    5   2.0       3   
1283         2                 1    3   4.0       2   
1284         5                 4    3   4.0       3   
1285         5                14    3  16.0       2   
1286         2                 1    5   2.0       3   
1287         2                 1    3   6.0       1   
1288         2                 1    5   4.0       2   
1289         1                 4   10   8.0       2   
1290         2                 1    1   6.0       1   
1291         2                 1    5   4.0       2   
1292         2                 1    5   2.0       2   
1293         2                 4    3   8.0       1   
1294         2                 4   11   6.0       1   
1295         2                 1    3   8.0       1   
1296         3                 1    5   2.0       3   
1297         2                 1    3   4.0       2   
1298         5                 4    3   4.0       3   
1299         5                14    3  16.0       2   
1300         2                 1    5   2.0       3   
1301         2                 1    3   6.0       1   
1302         2                 1    5   4.0       2   

                               Gpu  OpSys    Price  
0     Intel Iris Plus Graphics 640      2  Average  
1           Intel HD Graphics 6000      2  Average  
2            Intel HD Graphics 620      4      Low  
3               AMD Radeon Pro 455      2     High  
4     Intel Iris Plus Graphics 650      2     High  
5                    AMD Radeon R5      1      Low  
6          Intel Iris Pro Graphics      2     High  
7           Intel HD Graphics 6000      2  Average  
8             Nvidia GeForce MX150      1  Average  
9           Intel UHD Graphics 620      1      Low  
10          

### Gpu

In [19]:
list(data['Gpu'].unique())

['Intel Iris Plus Graphics 640',
 'Intel HD Graphics 6000',
 'Intel HD Graphics 620',
 'AMD Radeon Pro 455',
 'Intel Iris Plus Graphics 650',
 'AMD Radeon R5',
 'Intel Iris Pro Graphics',
 'Nvidia GeForce MX150',
 'Intel UHD Graphics 620',
 'Intel HD Graphics 520',
 'AMD Radeon Pro 555',
 'AMD Radeon R5 M430',
 'Intel HD Graphics 615',
 'AMD Radeon Pro 560',
 'Nvidia GeForce 940MX',
 'Intel HD Graphics 400',
 'Nvidia GeForce GTX 1050',
 'AMD Radeon R2',
 'AMD Radeon 530',
 'Nvidia GeForce 930MX',
 'Intel HD Graphics',
 'Intel HD Graphics 500',
 'Nvidia GeForce 930MX ',
 'Nvidia GeForce GTX 1060',
 'Nvidia GeForce 150MX',
 'Intel Iris Graphics 540',
 'AMD Radeon RX 580',
 'Nvidia GeForce 920MX',
 'AMD Radeon R4 Graphics',
 'AMD Radeon 520',
 'Nvidia GeForce GTX 1070',
 'Nvidia GeForce GTX 1050 Ti',
 'Nvidia GeForce MX130',
 'AMD R4 Graphics',
 'Nvidia GeForce GTX 940MX',
 'AMD Radeon RX 560',
 'Nvidia GeForce 920M',
 'AMD Radeon R7 M445',
 'AMD Radeon RX 550',
 'Nvidia GeForce GTX 1050M

In [20]:
data.loc[data['Gpu'].str.contains('Intel', na = False), 'Gpu'] = 1
data.loc[data['Gpu'].str.contains('AMD', na = False), 'Gpu'] = 2
data.loc[data['Gpu'].str.contains('Nvidia', na = False), 'Gpu'] = 3

list(data['Gpu'].unique())

[1, 2, 3]

### New CSV

In [21]:
data.to_csv('cleaned.csv')
data

TypeName  ScreenResolution  Cpu   Ram  Memory  Gpu  OpSys    Price
0            1                11    2   8.0       3    1      2  Average
1            1                 2    2   8.0       3    1      2  Average
2            2                 4    2   8.0       2    1      4      Low
3            1                13    3  16.0       2    2      2     High
4            1                11    2   8.0       2    1      2     High
5            2                 1   11   4.0       2    2      1      Low
6            1                13    3  16.0       2    1      2     High
7            1                 2    2   8.0       2    1      2  Average
8            1                 4    3  16.0       2    3      1  Average
9            1                 4    2   8.0       2    1      1      Low
10           2                 1    2   4.0       2    1      4      Low
11           2                 4    1   4.0       2    1      4      Low
12           1                13    3  16.0       2    2      2     High
13           2                 4    1   4.0       2    2      1      Low
14           1                 8   10   8.0       2    1      2  Average
15           1                11    2   8.0       2    1      2     High
16           2                 4    3   8.0       2    2      1      Low
17           1                13    3  16.0       2    2      2     High
18           2                 4    1   8.0       1    3      4      Low
19           1                 4    2   8.0       3    1      1  Average
20           3                 1    4   2.0       3    1      1      Low
21           4                 4    2   8.0       1    3      1  Average
22           2                 1   11   4.0       2    2      4      Low
23           5                 4    2   8.0       2    1      1  Average
24           1                 4    3   8.0       2    1      1      Low
25           2                 1    1   4.0       1    1      1      Low
26           1                 2    2   8.0       3    1      2  Average
27           2                 4    2   8.0       2    2      1  Average
28           1                 4    3   8.0       2    1      1  Average
29           2                 4    2   8.0       1    3      1  Average
...        ...               ...  ...   ...     ...  ...    ...      ...
1273         2                 1    3   6.0       1    2      1      Low
1274         2                 1    5   4.0       2    1      1      Low
1275         1                 4   10   8.0       2    1      1      Low
1276         2                 1    1   6.0       1    1      1      Low
1277         2                 1    5   4.0       2    1      3      Low
1278         2                 1    5   2.0       2    1      1      Low
1279         2                 4    3   8.0       1    3      1  Average
1280         2                 4   11   6.0       1    2      1      Low
1281         2                 1    3   8.0       1    2      3  Average
1282         3                 1    5   2.0       3    1      1      Low
1283         2                 1    3   4.0       2    3      1      Low
1284         5                 4    3   4.0       3    1      1      Low
1285         5                14    3  16.0       2    1      1  Average
1286         2                 1    5   2.0       3    1      1      Low
1287         2                 1    3   6.0       1    2      1      Low
1288         2                 1    5   4.0       2    1      1      Low
1289         1                 4   10   8.0       2    1      1      Low
1290         2                 1    1   6.0       1    1      1      Low
1291         2                 1    5   4.0       2    1      3      Low
1292         2                 1    5   2.0       2    1      1      Low
1293         2                 4    3   8.0       1    3      1  Average
1294         2                 4   11   6.0       1    2      1      Low
1295         2                 1    3   8.0       1    2      3 

## Classification

In [22]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

In [23]:
clean = pd.read_csv("cleaned.csv")
xHeader = list(data)
xHeader.remove('Price')
yHeader = ['Price']

list(data)

['TypeName',
 'ScreenResolution',
 'Cpu',
 'Ram',
 'Memory',
 'Gpu',
 'OpSys',
 'Price']

In [24]:
x = pd.DataFrame(columns=xHeader)
x.TypeName = clean.TypeName
#x.Inches = clean.Inches
x.ScreenResolution = clean.ScreenResolution
x.Cpu = clean.Cpu
x.Ram = clean.Ram
x.Memory = clean.Memory
x.Gpu = clean.Gpu
x.OpSys = clean.OpSys

y = pd.DataFrame(columns=yHeader)
y.Price = clean.Price

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=400)
gnb = GaussianNB()
gnb = gnb.fit(x_train, np.ravel(y_train, order = 'C'))
y_pred = gnb.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.7085889570552147

np.ravel is used to flatten the array.

In [26]:
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

    Average       0.65      0.65      0.65       128
       High       0.59      0.69      0.64        71
        Low       0.85      0.78      0.81       127

avg / total       0.72      0.71      0.71       326

[[83 29 16]
 [21 49  1]
 [23  5 99]]


In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=400)
mnb = MultinomialNB()
mnb = mnb.fit(x_train, np.ravel(y_train, order = 'C'))
y_pred = mnb.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.6349693251533742

In [28]:
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

    Average       0.54      0.70      0.61       128
       High       0.58      0.46      0.52        71
        Low       0.83      0.66      0.74       127

avg / total       0.66      0.63      0.64       326

[[90 23 15]
 [36 33  2]
 [42  1 84]]


In [29]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=400)
bnb = BernoulliNB()
bnb = bnb.fit(x_train, np.ravel(y_train, order = 'C'))
y_pred = bnb.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.3895705521472393

In [30]:
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

    Average       0.00      0.00      0.00       128
       High       0.00      0.00      0.00        71
        Low       0.39      1.00      0.56       127

avg / total       0.15      0.39      0.22       326

[[  0   0 128]
 [  0   0  71]
 [  0   0 127]]


c:\python27\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
num_array = list()
print("Enter the vector form of the specifications")
n=input("Type Name  \n1 - Ultrabook\n2 - Notebook\n3 - Netbook\n4 - Gaming\n5 - 2 in 1 Convertible\n6 - Workstation\nEnter Type Number (1-6):")
num_array.append(int(n))
n=input("\n\nScreen Resolution \n1 - 1366x768\n2 - 1440x900\n3 - 1600x900\n4 - 1920x1080\n5 - 1920x1200\n6 - 2160x1440\n7 - 2256x1504\n8 - 2304x1440\n9 - 2400x1600\n10 - 2560x1440\n11 - 2560x1600\n12 - 2736x1824\n13 - 2880x1800\n14 - 3200x1800\n15 - 3840x2160\nEnter Screen Resolution (1-15):")
num_array.append(int(n))
n=input("\n\nCentral Processing Unit(CPU) \n1 - i3\n2 - i5\n3 - i7\n4 - Atom\n5 - Celeron Dual Core\n6 - Celeron Quad Core\n7 - Pentium Dual Core\n8 - Pentium Quad Core\n9 - Xeon\n10 - Core M\n11 - AMD\nEnter CPU:")
num_array.append(int(n))
n=input("\n\nEnter RAM in GB(eg. 4, 8, 16 etc.):")
num_array.append(float(n))
n=input("\n\nMemory \n1 - High Memory (>=1TB)\n2 - Average(>200GB)\n3 - Low Memory(=<200GB)\nEnter Memory:")
num_array.append(int(n))
n=input("\n\nGraphics Processing Unit (GPU)\n1 - Intel Graphics (HD,UHD)\n2 - AMD\n3 - Nvidia\nEnter GPU:")
num_array.append(int(n))
n=input("\n\nOperating System \n1 - Windows\n2 - Mac\n3 - Linux\n4 - Others\nEnter GPU:")
num_array.append(int(n))

instance = np.reshape(num_array, (1,-1))

print("\n")
print(" Low -> 0-799 euros\n Average -> 800-1499 euros\n High 1500 euros and above\n ")
predictions = mnb.predict(instance)[0]
print("MonomialNB Price Range Prediction: ", predictions)
predictions = gnb.predict(instance)[0]
print("GaussianNB Price Range Prediction: ", predictions)
predictions = bnb.predict(instance)[0]
print("BernoulliNB Price Range Prediction: ", predictions)

Enter the vector form of the specifications
